### ISSUE TITLE
Hash Collision due to bug in hashing algorithm

### ISSUE THREAD

**Issue by OGrohmann** [ScalefreeCOM/datavault4dbt#109]
In datavault4dbt with Snowflake we have identified a hash collision for values with small 'v'. Example:  0Q03Y0000033lviSAA and 0Q03Y0000033liSAA produce the same hash.
The issue seems to be caused by the REGEXP_REPLACE expression that should replace the '\v' values. However, it is also replacing any small 'v' letters which is not correct.
Same issue might be valid for n, t and r characters (haven't checked though).

**Comment by tkirschke** [comment]
Hi @OGrohmann and thanks for reaching out!

Me and my colleague @thoffmann-sf will investigate this and work on a fast solution!

Best regards
Tim

**Comment by bschlottfeldt** [comment]
The issue is only valid for the 'v' character.
Thank you for noticing!! We are going to work on the solution

**Comment by thoffmann-sf** [comment]
Hi @OGrohmann thanks for point out the issue!

we've identified the problem and a hotfix #118 is already waiting for approval.
The problem was that Snowflake does not use the \v identifier for vertical tabs (In the way we implemented it at least), the REGEX_REPLACE now uses the ASCII identifier to replace a vertical tab, once the hotfix is approved.

Best regards,
Tim
