### ISSUE TITLE
Redshift timestamp conversion creates timestamptz instead of timestamp

### ISSUE THREAD

**Issue by horony** [ScalefreeCOM/datavault4dbt#212]
Hi everyone,

we think that the Redshift implementation of datavault4dbt uses a wrong TIMESTAMP conversion in several locations. Instead of expected TIMESTAMPs, TIMESTAMPTZs are created. Causing several issuses.

Main cause is the Redshifts function `TO_TIMESTAMP` does **not** create a TIMESTAMP but a TIMESTAMPTZ (see https://docs.aws.amazon.com/redshift/latest/dg/r_TO_TIMESTAMP.html). One possible solution would be to use another Redshift function.

Two examples where `TO_TIMESTAMP` is used:
https://github.com/ScalefreeCOM/datavault4dbt/blob/679a736d28210f5329438a2b34ee8ad11ce04384/macros/supporting/string_to_timestamp.sql#L22 https://github.com/ScalefreeCOM/datavault4dbt/blob/679a736d28210f5329438a2b34ee8ad11ce04384/macros/tables/redshift/control_snap_v0.sql#L10

Some dependend functions are also effected. For example the ghost record-macro will not be able to detect TIMESTAMPs as they are all TIMESTAMPTZ.

https://github.com/ScalefreeCOM/datavault4dbt/blob/49079089527fe8759a29f16f330bdf7ddd753c88/macros/supporting/ghost_record_per_datatype.sql#L30

Issue was created after discussing this problem with @marcfinger @Lennart-Bu @hrevale 

Best,

Lennart

**Comment by tkiehn** [comment]
Hi Lennart and thanks for reaching out!

If I understand correctly issues are caused because in some places `TIMESTAMP` and in others `TIMESTAMPTZ` are used by the package? Or do they come up because of the datatype of the source data?

Currently we are developing a feature to enable setting a default timestamp datatype in the `dbt_project.yml`.

Regarding the ghost-record detection, in the branch `redshift-patch` this is addressed already: [Link](https://github.com/ScalefreeCOM/datavault4dbt/blob/1fb0544ea55776151f8dca70c1edc8083c17624b/macros/supporting/ghost_record_per_datatype.sql#L363)
(Even though I see the `TO_TIMESTAMP`-method is used there as well.)

I am looking forward to further help you resolve any problems.

Best Regards,
Theo

**Comment by tkiehn** [comment]
Hi @horony,

a little update from our side:

With the upcoming release of datavault4dbt v1.4.0 this issue has been addressed by introducing a new global variable for setting the `timestamp_default_dtype`.
The `string_to_timestamp`-macro of redshift will cast the result of the `TO_TIMESTAMP` method according to the value that was set inside the `dbt_project.yml`.

Kind regards
Theo
